title: i-am-not-kangjik
markdown: kramdown

# for atom feed
author:
  name: Kangjik Kim
  email: rkqqkb@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

baseurl: "https://i-am-not-kangjik.github.io/"


google_site_verification: PgIs2wRUYdrvbcINZz2P-COS_yZn3FntsInGtjt7hj8